name: Record Checker
on:
  schedule:
    - cron: '*/15 * * * *' # 5分おき（※混雑時は少し遅れることがあります）
  workflow_dispatch:      # 手動実行ボタンも追加

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - name: Install dependencies
        run: |
          pip install google-generativeai twikit
      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python app.py
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update records" || exit 0
          git push
